/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hk7wVxkIy5d
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:
 
 import { Inter } from 'next/font/google'
 
 inter({
 subsets: ['latin'],
 display: 'swap',
 })
 
 To read more about using these font, please visit the Next.js documentation:
 - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
 - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
 **/
import Link from "next/link"
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger
} from "@/components/ui/dialog"
import {Button} from "@/components/ui/button"
import {Label} from "@/components/ui/label"
import {Input} from "@/components/ui/input"
import {Card, CardContent, CardDescription, CardHeader, CardTitle} from "@/components/ui/card"
import {Avatar, AvatarFallback, AvatarImage} from "@/components/ui/avatar"

export function Component() {
    return (
        <div className="flex flex-col min-h-screen bg-background">
            <header className="flex items-center justify-between h-16 px-6 border-b border-muted">
                <Link href="#" className="flex items-center gap-2 text-lg font-semibold" prefetch={false}>
                    <ClockIcon className="w-6 h-6"/>
                    <span>Time Tracker</span>
                </Link>
                <div className="flex items-center gap-4">
                    <Dialog>
                        <DialogTrigger asChild>
                            <Button variant="outline">Login</Button>
                        </DialogTrigger>
                        <DialogContent className="sm:max-w-[425px]">
                            <DialogHeader>
                                <DialogTitle>Login</DialogTitle>
                                <DialogDescription>Enter your login credentials to access the Time
                                    Tracker.</DialogDescription>
                            </DialogHeader>
                            <div className="grid gap-4 py-4">
                                <div className="space-y-2">
                                    <Label htmlFor="email">Email</Label>
                                    <Input id="email" type="email" placeholder="m@example.com" required/>
                                </div>
                                <div className="space-y-2">
                                    <Label htmlFor="password">Password</Label>
                                    <Input id="password" type="password" required/>
                                </div>
                            </div>
                            <DialogFooter>
                                <Button type="submit">Login</Button>
                            </DialogFooter>
                        </DialogContent>
                    </Dialog>
                    <Button variant="ghost" size="icon">
                        <SettingsIcon className="w-5 h-5"/>
                        <span className="sr-only">Settings</span>
                    </Button>
                </div>
            </header>
            <main className="flex-1 flex flex-col items-center justify-center gap-8 p-4 md:p-8">
                <div className="bg-card rounded-lg shadow-lg p-8 w-full max-w-md flex flex-col items-center gap-6">
                    <div className="text-6xl font-bold">
                        <span className="text-primary">9:41</span>
                        <span className="text-muted-foreground">AM</span>
                    </div>
                    <div className="flex gap-4">
                        <Button size="lg">Clock In</Button>
                        <Button variant="outline" size="lg">
                            Clock Out
                        </Button>
                    </div>
                </div>
                <Card className="w-full max-w-md">
                    <CardHeader>
                        <CardTitle>Today's Check-ins</CardTitle>
                        <CardDescription>View who has clocked in for the day.</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <div className="grid gap-4">
                            <div className="flex items-center justify-between">
                                <div className="flex items-center gap-2">
                                    <Avatar className="border">
                                        <AvatarImage src="/placeholder-user.jpg"/>
                                        <AvatarFallback>JD</AvatarFallback>
                                    </Avatar>
                                    <div>
                                        <div className="font-medium">John Doe</div>
                                        <div className="text-sm text-muted-foreground">Clocked in at 9:00 AM</div>
                                    </div>
                                </div>
                                <Button
                                    variant="ghost"
                                    size="icon"
                                    onClick={() => {
                                        return (
                                            <Dialog>
                                                <DialogTrigger asChild>
                                                    <Button variant="ghost" size="icon">
                                                        <ChevronRightIcon className="w-4 h-4"/>
                                                    </Button>
                                                </DialogTrigger>
                                                <DialogContent className="max-w-md">
                                                    <DialogHeader>
                                                        <DialogTitle>John Doe</DialogTitle>
                                                        <DialogDescription>More information about the clocked
                                                            person</DialogDescription>
                                                    </DialogHeader>
                                                    <div>
                                                        <div className="grid gap-4">
                                                            <div className="flex items-center gap-2">
                                                                <Avatar className="border">
                                                                    <AvatarImage src="/placeholder-user.jpg"/>
                                                                    <AvatarFallback>JD</AvatarFallback>
                                                                </Avatar>
                                                                <div>
                                                                    <div className="font-medium">John Doe</div>
                                                                    <div
                                                                        className="text-sm text-muted-foreground">Software
                                                                        Engineer
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div className="grid gap-1">
                                                                <div className="flex items-center justify-between">
                                                                    <div className="text-muted-foreground">Clocked in
                                                                        at:
                                                                    </div>
                                                                    <div>9:00 AM</div>
                                                                </div>
                                                                <div className="flex items-center justify-between">
                                                                    <div className="text-muted-foreground">Total hours
                                                                        worked:
                                                                    </div>
                                                                    <div>2h 30m</div>
                                                                </div>
                                                                <div className="flex items-center justify-between">
                                                                    <div className="text-muted-foreground">Last break:
                                                                    </div>
                                                                    <div>10:30 AM</div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <DialogFooter>
                                                        <div>
                                                            <Button variant="ghost">Close</Button>
                                                        </div>
                                                    </DialogFooter>
                                                </DialogContent>
                                            </Dialog>
                                        )
                                    }}
                                >
                                    <ChevronRightIcon className="w-4 h-4"/>
                                </Button>
                            </div>
                            <div className="flex items-center justify-between">
                                <div className="flex items-center gap-2">
                                    <Avatar className="border">
                                        <AvatarImage src="/placeholder-user.jpg"/>
                                        <AvatarFallback>JA</AvatarFallback>
                                    </Avatar>
                                    <div>
                                        <div className="font-medium">Jane Appleseed</div>
                                        <div className="text-sm text-muted-foreground">Clocked in at 9:15 AM</div>
                                    </div>
                                </div>
                                <Button
                                    variant="ghost"
                                    size="icon"
                                    onClick={() => {
                                        return (
                                            <Dialog>
                                                <DialogTrigger asChild>
                                                    <Button variant="ghost" size="icon">
                                                        <ChevronRightIcon className="w-4 h-4"/>
                                                    </Button>
                                                </DialogTrigger>
                                                <DialogContent className="max-w-md">
                                                    <DialogHeader>
                                                        <DialogTitle>Jane Appleseed</DialogTitle>
                                                        <DialogDescription>More information about the clocked
                                                            person</DialogDescription>
                                                    </DialogHeader>
                                                    <div>
                                                        <div className="grid gap-4">
                                                            <div className="flex items-center gap-2">
                                                                <Avatar className="border">
                                                                    <AvatarImage src="/placeholder-user.jpg"/>
                                                                    <AvatarFallback>JA</AvatarFallback>
                                                                </Avatar>
                                                                <div>
                                                                    <div className="font-medium">Jane Appleseed</div>
                                                                    <div
                                                                        className="text-sm text-muted-foreground">Product
                                                                        Manager
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div className="grid gap-1">
                                                                <div className="flex items-center justify-between">
                                                                    <div className="text-muted-foreground">Clocked in
                                                                        at:
                                                                    </div>
                                                                    <div>9:15 AM</div>
                                                                </div>
                                                                <div className="flex items-center justify-between">
                                                                    <div className="text-muted-foreground">Total hours
                                                                        worked:
                                                                    </div>
                                                                    <div>2h 15m</div>
                                                                </div>
                                                                <div className="flex items-center justify-between">
                                                                    <div className="text-muted-foreground">Last break:
                                                                    </div>
                                                                    <div>10:45 AM</div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <DialogFooter>
                                                        <div>
                                                            <Button variant="ghost">Close</Button>
                                                        </div>
                                                    </DialogFooter>
                                                </DialogContent>
                                            </Dialog>
                                        )
                                    }}
                                >
                                    <ChevronRightIcon className="w-4 h-4"/>
                                </Button>
                            </div>
                            <div className="flex items-center justify-between">
                                <div className="flex items-center gap-2">
                                    <Avatar className="border">
                                        <AvatarImage src="/placeholder-user.jpg"/>
                                        <AvatarFallback>SM</AvatarFallback>
                                    </Avatar>
                                    <div>
                                        <div className="font-medium">Sarah Musk</div>
                                        <div className="text-sm text-muted-foreground">Clocked in at 9:30 AM</div>
                                    </div>
                                </div>
                                <Button
                                    variant="ghost"
                                    size="icon"
                                    onClick={() => {
                                        return (
                                            <Dialog>
                                                <DialogTrigger asChild>
                                                    <Button variant="ghost" size="icon">
                                                        <ChevronRightIcon className="w-4 h-4"/>
                                                    </Button>
                                                </DialogTrigger>
                                                <DialogContent className="max-w-md">
                                                    <DialogHeader>
                                                        <DialogTitle>Sarah Musk</DialogTitle>
                                                        <DialogDescription>More information about the clocked
                                                            person</DialogDescription>
                                                    </DialogHeader>
                                                    <div>
                                                        <div className="grid gap-4">
                                                            <div className="flex items-center gap-2">
                                                                <Avatar className="border">
                                                                    <AvatarImage src="/placeholder-user.jpg"/>
                                                                    <AvatarFallback>SM</AvatarFallback>
                                                                </Avatar>
                                                                <div>
                                                                    <div className="font-medium">Sarah Musk</div>
                                                                    <div
                                                                        className="text-sm text-muted-foreground">Designer
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div className="grid gap-1">
                                                                <div className="flex items-center justify-between">
                                                                    <div className="text-muted-foreground">Clocked in
                                                                        at:
                                                                    </div>
                                                                    <div>9:30 AM</div>
                                                                </div>
                                                                <div className="flex items-center justify-between">
                                                                    <div className="text-muted-foreground">Total hours
                                                                        worked:
                                                                    </div>
                                                                    <div>2h</div>
                                                                </div>
                                                                <div className="flex items-center justify-between">
                                                                    <div className="text-muted-foreground">Last break:
                                                                    </div>
                                                                    <div>11:00 AM</div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <DialogFooter>
                                                        <div>
                                                            <Button variant="ghost">Close</Button>
                                                        </div>
                                                    </DialogFooter>
                                                </DialogContent>
                                            </Dialog>
                                        )
                                    }}
                                >
                                    <ChevronRightIcon className="w-4 h-4"/>
                                </Button>
                            </div>
                        </div>
                    </CardContent>
                </Card>
            </main>
        </div>
    )
}

function ChevronRightIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="m9 18 6-6-6-6"/>
        </svg>
    )
}


function ClockIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <circle cx="12" cy="12" r="10"/>
            <polyline points="12 6 12 12 16 14"/>
        </svg>
    )
}


function SettingsIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path
                d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"/>
            <circle cx="12" cy="12" r="3"/>
        </svg>
    )
}


function XIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M18 6 6 18"/>
            <path d="m6 6 12 12"/>
        </svg>
    )
}
